// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbSQrI14oGRW0wvMoMkZLWjS8b2pP8RQI',
    appId: '1:541589841536:web:103c2dea7e52e8790be865',
    messagingSenderId: '541589841536',
    projectId: 'smart-108',
    authDomain: 'smart-108.firebaseapp.com',
    storageBucket: 'smart-108.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5_xXqNFEQDlM9C1NayBjfLmbCXzknjfI',
    appId: '1:541589841536:android:b2d463c87fb801590be865',
    messagingSenderId: '541589841536',
    projectId: 'smart-108',
    storageBucket: 'smart-108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0wU2rKnJePnGsxH55Upp22-7NNeB-HOk',
    appId: '1:541589841536:ios:eff6eb3055eb1fcc0be865',
    messagingSenderId: '541589841536',
    projectId: 'smart-108',
    storageBucket: 'smart-108.firebasestorage.app',
    androidClientId: '541589841536-7b42i4eqbvi08c959b97ed1lomqs0kd8.apps.googleusercontent.com',
    iosClientId: '541589841536-c6rd9538hsaa9ihe83jgs544ecvg7u7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.smart108Responders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0wU2rKnJePnGsxH55Upp22-7NNeB-HOk',
    appId: '1:541589841536:ios:eff6eb3055eb1fcc0be865',
    messagingSenderId: '541589841536',
    projectId: 'smart-108',
    storageBucket: 'smart-108.firebasestorage.app',
    androidClientId: '541589841536-7b42i4eqbvi08c959b97ed1lomqs0kd8.apps.googleusercontent.com',
    iosClientId: '541589841536-c6rd9538hsaa9ihe83jgs544ecvg7u7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.smart108Responders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbSQrI14oGRW0wvMoMkZLWjS8b2pP8RQI',
    appId: '1:541589841536:web:a1d2e863b5dc4d350be865',
    messagingSenderId: '541589841536',
    projectId: 'smart-108',
    authDomain: 'smart-108.firebaseapp.com',
    storageBucket: 'smart-108.firebasestorage.app',
  );

}